import crypto from 'crypto';

const ALGORITHM = 'aes-256-gcm';
// The encryption key must be a 32-byte string set via env variable.
function getEncryptionKey(): Buffer {
  const secret = process.env.ENCRYPTION_KEY;
  if (!secret) {
    throw new Error('ENCRYPTION_KEY environment variable is required. Please set it in your environment/Vercel dashboard.');
  }
  
  if (Buffer.byteLength(secret) === 32) {
    return Buffer.from(secret);
  }
  
  // If it's a hex string (64 chars) or base64 (44 chars), decode it.
  // Otherwise, just hash it to get 32 bytes for ease of use.
  return crypto.createHash('sha256').update(secret).digest();
}

/**
 * Encrypts a string using AES-256-GCM.
 * Returns a payload string containing iv:authTag:encryptedData (hex encoded).
 */
export function encryptString(text: string): string {
  if (!text) return text;
  
  try {
    const key = getEncryptionKey();
    const iv = crypto.randomBytes(16);
    const cipher = crypto.createCipheriv(ALGORITHM, key, iv);
    
    let encrypted = cipher.update(text, 'utf8', 'hex');
    encrypted += cipher.final('hex');
    
    const authTag = cipher.getAuthTag().toString('hex');
    const ivHex = iv.toString('hex');
    
    return `${ivHex}:${authTag}:${encrypted}`;
  } catch (error) {
    console.error('Encryption error:', error);
    throw new Error('Failed to encrypt data');
  }
}

/**
 * Decrypts a payload string generated by encryptString.
 */
export function decryptString(payload: string): string {
  if (!payload || !payload.includes(':')) {
    // If it's not our encrypted format (e.g. legacy plain text), return as-is
    // This allows gradual migration of existing tokens
    return payload;
  }
  
  try {
    const parts = payload.split(':');
    if (parts.length !== 3) return payload; // Not our format
    
    const [ivHex, authTagHex, encryptedHex] = parts;
    if (!ivHex || !authTagHex || !encryptedHex) return payload;

    const key = getEncryptionKey();
    const iv = Buffer.from(ivHex, 'hex');
    const authTag = Buffer.from(authTagHex, 'hex');
    
    const decipher = crypto.createDecipheriv(ALGORITHM, key, iv);
    decipher.setAuthTag(authTag);
    
    let decrypted: string = decipher.update(encryptedHex, 'hex', 'utf8');
    decrypted += decipher.final('utf8');
    
    return decrypted;
  } catch (error) {
    console.error('Decryption error:', error);
    // Return original string on failure just in case it was a plaintext string that happened to have colons
    return payload;
  }
}
