-- Enable Row Level Security on all tables to prevent unauthorized access

ALTER TABLE "account" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "live_account_transaction" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "master_account" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "payout" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "phase_account" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "admin_feature_flag" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "admin_sharing_policy" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "user" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "user_settings" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "import_job" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "notification" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "feedback" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "user_geo_log" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "shared_report" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "subscription" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "synchronization" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "daily_note" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "journal_template" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "weekly_review" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "trade" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "trade_execution" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "trade_tag" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "trading_model" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "activity_log" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "user_goal" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "breach_record" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "daily_anchor" ENABLE ROW LEVEL SECURITY;

-- Base Policies (Examples where user_id exists)

CREATE POLICY "Users can view their own data" ON "account" FOR SELECT USING (auth.uid()::text = "userId");
CREATE POLICY "Users can insert their own data" ON "account" FOR INSERT WITH CHECK (auth.uid()::text = "userId");
CREATE POLICY "Users can update their own data" ON "account" FOR UPDATE USING (auth.uid()::text = "userId");
CREATE POLICY "Users can delete their own data" ON "account" FOR DELETE USING (auth.uid()::text = "userId");

CREATE POLICY "Users can view their own data" ON "trade" FOR SELECT USING (auth.uid()::text = "userId");
CREATE POLICY "Users can insert their own data" ON "trade" FOR INSERT WITH CHECK (auth.uid()::text = "userId");
CREATE POLICY "Users can update their own data" ON "trade" FOR UPDATE USING (auth.uid()::text = "userId");
CREATE POLICY "Users can delete their own data" ON "trade" FOR DELETE USING (auth.uid()::text = "userId");

-- (Additional specific policies for each table can be generated by migrations, but RLS is now strict-by-default)
